#!/bin/bash

# Quick Start Script for Site Password Protector Extension

echo "================================================"
echo "Site Password Protector - Installation Guide"
echo "================================================"
echo ""

echo "📦 Extension files created successfully!"
echo ""

echo "📋 Files in your extension:"
echo "  ✓ manifest.json (Chrome version)"
echo "  ✓ manifest_firefox.json (Firefox version)"
echo "  ✓ background.js"
echo "  ✓ content.js"
echo "  ✓ popup.html, popup.css, popup.js"
echo "  ✓ icons/ (icon16.png, icon48.png, icon128.png)"
echo "  ✓ README.md"
echo ""

echo "🚀 INSTALLATION INSTRUCTIONS"
echo ""
echo "═══════════════════════════════════════════════"
echo "FOR CHROME:"
echo "═══════════════════════════════════════════════"
echo "1. Open Chrome browser"
echo "2. Go to: chrome://extensions/"
echo "3. Enable 'Developer mode' (toggle in top-right)"
echo "4. Click 'Load unpacked'"
echo "5. Select this folder: $(pwd)"
echo "6. Done! The extension icon will appear in toolbar"
echo ""

echo "═══════════════════════════════════════════════"
echo "FOR FIREFOX:"
echo "═══════════════════════════════════════════════"
echo "1. First rename manifest_firefox.json to manifest.json:"
echo "   mv manifest.json manifest_chrome.json"
echo "   mv manifest_firefox.json manifest.json"
echo ""
echo "2. Open Firefox browser"
echo "3. Go to: about:debugging#/runtime/this-firefox"
echo "4. Click 'Load Temporary Add-on'"
echo "5. Select the manifest.json file from this folder"
echo "6. Done! (Note: temporary, will be removed when Firefox closes)"
echo ""

echo "═══════════════════════════════════════════════"
echo "USAGE:"
echo "═══════════════════════════════════════════════"
echo "1. Click the extension icon in browser toolbar"
echo "2. Enter a website domain (e.g., facebook.com)"
echo "3. Set a password for that site"
echo "4. Click 'Add Site'"
echo "5. Visit the site - you'll need the password!"
echo ""

echo "💡 TIPS:"
echo "  • Don't include http://, https://, or www in domain"
echo "  • Sessions last 30 minutes after login"
echo "  • You can manage sites from the extension popup"
echo "  • Passwords are stored securely in browser storage"
echo ""

echo "📖 For more details, see README.md"
echo ""
echo "✨ Happy browsing securely!"
echo "================================================"
